# Generated by Django 5.1.4 on 2025-01-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_location_alter_item_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="is_valuable",
        ),
    ]
