# Generated by Django 5.1.4 on 2025-01-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_item_is_valuable"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="barcode",
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
    ]
