# Generated by Django 5.1.4 on 2025-01-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_item_category_alter_item_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="welcome_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
