# Generated by Django 5.1.4 on 2025-01-08 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_message_chat_chatroom_message_room_and_more"),
        ("users", "0004_merge_20241229_1953"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="item_description",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chatrooms",
                to="users.item",
            ),
        ),
    ]
